# CodSoft Data Analytics Internship - Task 1

## Data Cleaning and Preprocessing

### Dataset: Retail Sales Data

This project focuses on cleaning and preprocessing a retail sales dataset using Python and Pandas.

### Objectives
- Import and inspect the dataset
- Identify missing values
- Identify duplicate records
- Detect inconsistent data entries
- Correct data types
- Clean and preprocess the dataset
- Save the cleaned dataset for further analysis

### Tools Used
- Python
- Pandas
- NumPy
- Jupyter Notebook

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("CODSOFT_Task1_Retail_Sales_Raw.csv")
df.head()

,Transaction_ID,Date,Customer_Name,Category,Quantity,Unit_Price,Payment_Method
0,1001,2026-01-02,Ananya,Electronics,2.0,1200,UPI
1,1002,2026-01-03,Rahul,Clothing,1.0,800,Card
2,1003,2026-01-05,Priya,Beauty,3.0,450,Cash
3,1004,2026-01-07,Arjun,Electronics,1.0,2500,UPI
4,1005,2026-01-09,Sneha,Home,2.0,1500,Card

In [3]:
df.shape

(42, 7)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  42 non-null     int64
 1   Date            42 non-null     str
 2   Customer_Name   41 non-null     str
 3   Category        42 non-null     str
 4   Quantity        41 non-null     float64
 5   Unit_Price      42 non-null     str
 6   Payment_Method  41 non-null     str
dtypes: float64(1), int64(1), str(5)
memory usage: 3.7 KB

In [5]:
df.isnull().sum()

Transaction_ID    0
Date              0
Customer_Name     1
Category          0
Quantity          1
Unit_Price        0
Payment_Method    1
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(2)

In [7]:
df[df.duplicated()]

,Transaction_ID,Date,Customer_Name,Category,Quantity,Unit_Price,Payment_Method
40,1003,2026-01-05,Priya,Beauty,3.0,450,Cash
41,1016,2026-02-01,Ananya,Clothing,3.0,750,Cash

In [8]:
df = df.drop_duplicates()

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.isnull().sum()

Transaction_ID    0
Date              0
Customer_Name     1
Category          0
Quantity          1
Unit_Price        0
Payment_Method    1
dtype: int64

In [11]:
df[df.isnull().any(axis=1)]

,Transaction_ID,Date,Customer_Name,Category,Quantity,Unit_Price,Payment_Method
5,1006,2026-01-11,NaN,Clothing,4.0,700,Cash
16,1017,2026-02-03,Rahul,Beauty,1.0,550,NaN
27,1028,2026-02-25,Aarav,Clothing,NaN,850,Card

In [12]:
df["Quantity"].median()

np.float64(2.0)

In [13]:
df["Customer_Name"] = df["Customer_Name"].fillna("Unknown")

df["Payment_Method"] = df["Payment_Method"].fillna("Unknown")

df["Quantity"] = df["Quantity"].fillna(df["Quantity"].median())

In [14]:
df.isnull().sum()

Transaction_ID    0
Date              0
Customer_Name     0
Category          0
Quantity          0
Unit_Price        0
Payment_Method    0
dtype: int64

In [18]:
df["Category"].unique()

<ArrowStringArray>
['Electronics', 'Clothing', 'Beauty', 'Home']
Length: 4, dtype: str

In [20]:
df["Payment_Method"].unique()

<ArrowStringArray>
['UPI', 'Card', 'Cash', 'Unknown']
Length: 4, dtype: str

In [17]:
df["Category"] = df["Category"].replace({
    "home": "Home",
    "ELECTRONICS": "Electronics"
})

In [19]:
df["Payment_Method"] = df["Payment_Method"].replace({
    "upi": "UPI"
})

In [21]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

In [22]:
df["Date"].dtype

dtype('<M8[us]')

In [23]:
df["Unit_Price"].unique()

<ArrowStringArray>
[   '1200',     '800',     '450',    '2500',    '1500',     '700',     '600',
    '1800',     '900',     '650',    '2200',     '500',    '1300',    '1600',
     '750',     '550',    '2100',    '1900',    '1100', '700 INR',    '2400',
    '1400',     '850',    '1700',    '1250',    '2000',    '1450',     '780',
    '2300',    '1350',     '820']
Length: 31, dtype: str

In [24]:
df["Unit_Price"] = df["Unit_Price"].astype(str).str.replace(" INR", "", regex=False).str.strip()

df["Unit_Price"] = pd.to_numeric(df["Unit_Price"], errors="coerce")

In [25]:
df["Unit_Price"].dtype

dtype('int64')

In [26]:
df.dtypes

Transaction_ID             int64
Date              datetime64[us]
Customer_Name                str
Category                     str
Quantity                 float64
Unit_Price                 int64
Payment_Method               str
dtype: object

In [27]:
df.isnull().sum()

Transaction_ID    0
Date              1
Customer_Name     0
Category          0
Quantity          0
Unit_Price        0
Payment_Method    0
dtype: int64

In [28]:
df[df["Date"].isnull()]

,Transaction_ID,Date,Customer_Name,Category,Quantity,Unit_Price,Payment_Method
12,1013,NaT,Aarav,Home,4.0,1300,Cash

In [29]:
raw_df = pd.read_csv("CODSOFT_Task1_Retail_Sales_Raw.csv")

raw_df[raw_df["Transaction_ID"] == 1013]

,Transaction_ID,Date,Customer_Name,Category,Quantity,Unit_Price,Payment_Method
12,1013,27/01/2026,Aarav,Home,4.0,1300,Cash

In [30]:
df["Date"] = pd.to_datetime(df["Date"], dayfirst=True, errors="coerce")

In [31]:
df["Date"].isnull().sum()

np.int64(1)

In [32]:
df[df["Date"].isnull()]

,Transaction_ID,Date,Customer_Name,Category,Quantity,Unit_Price,Payment_Method
12,1013,NaT,Aarav,Home,4.0,1300,Cash

In [33]:
df.loc[df["Transaction_ID"] == 1013, "Date"] = pd.Timestamp("2026-01-27")

In [34]:
df["Date"].isnull().sum()

np.int64(0)

In [35]:
df.isnull().sum()

Transaction_ID    0
Date              0
Customer_Name     0
Category          0
Quantity          0
Unit_Price        0
Payment_Method    0
dtype: int64

In [36]:
df.duplicated().sum()

np.int64(0)

In [37]:
df.to_csv("CODSOFT_Task1_Retail_Sales_Cleaned.csv", index=False)

In [38]:
import os
os.path.exists("CODSOFT_Task1_Retail_Sales_Cleaned.csv")

True

In [39]:
df.head(10)

,Transaction_ID,Date,Customer_Name,Category,Quantity,Unit_Price,Payment_Method
0,1001,2026-01-02,Ananya,Electronics,2.0,1200,UPI
1,1002,2026-01-03,Rahul,Clothing,1.0,800,Card
2,1003,2026-01-05,Priya,Beauty,3.0,450,Cash
3,1004,2026-01-07,Arjun,Electronics,1.0,2500,UPI
4,1005,2026-01-09,Sneha,Home,2.0,1500,Card
5,1006,2026-01-11,Unknown,Clothing,4.0,700,Cash
6,1007,2026-01-13,Kavya,Beauty,2.0,600,UPI
7,1008,2026-01-15,Rohan,Electronics,1.0,1800,Card
8,1009,2026-01-17,Meera,Home,3.0,900,UPI
9,1010,2026-01-19,Aditya,Clothing,2.0,650,Cash